// Copyright (c) Spekt Contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated>
// Skip code analysis errors.
// </auto-generated>

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Json.TestLogger")]
[assembly: InternalsVisibleTo("Json.TestAdapter")]
[assembly: InternalsVisibleTo("TestLogger.UnitTests")]
[assembly: ExcludeFromCodeCoverage]
