<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger</AssemblyName>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <PropertyGroup Label="Configuration">
    <RootNamespace>Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="obj/**;bin/**;JUnitXmlTestLogger.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TestLogger/TestLogger.MTP.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Platform" />
  </ItemGroup>

</Project>
